# Generated by Django 4.0.2 on 2022-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, default=1),
        ),
    ]
