# Generated by Django 4.0.2 on 2022-02-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
